resources:
- cluster-api-ipam-provider-in-cluster.yaml
- cluster-api-provider-proxmox.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- etcd-backup-operator.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
