resources:
- cluster-api-ipam-provider-in-cluster.yaml
- cluster-api-provider-proxmox.yaml
- dashboards.yaml
- deletion-blocker-operator.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- etcd-backup-operator.yaml
- exception-recommender.yaml
- falco.yaml
- fluent-logshipping-app.yaml
- keda.yaml
- konfiguration.v2.yaml
- kyverno-policies-connectivity.yaml
- loki.yaml
- mimir.yaml
- plugin-barman-cloud.yaml
- prometheus-remotewrite.yaml
- rbac-operator.yaml
- silence-operator.yaml
- starboard-exporter.yaml
- teleport-operator.yaml
- tempo.yaml
- trivy-operator.yaml
- trivy.yaml
