resources:
- cluster-api-ipam-provider-in-cluster.yaml
- cluster-api-provider-proxmox.yaml
- dex-app.yaml
- dex-operator.yaml
- dns-operator-route53.yaml
- konfiguration.v2.yaml
- teleport-operator.yaml
- trivy-operator.yaml
